/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./../components/Auth/index.vue')['default']
    AuthAll: typeof import('./../components/AuthAll/index.vue')['default']
    ColSetting: typeof import('./../components/ProTable/components/ColSetting.vue')['default']
    FileUpload: typeof import('./../components/FileUpload/index.vue')['default']
    FixedActionBar: typeof import('./../components/FixedActionBar/index.vue')['default']
    Grid: typeof import('./../components/Grid/index.vue')['default']
    GridItem: typeof import('./../components/Grid/components/GridItem.vue')['default']
    HButton: typeof import('./../layouts/ui-kit/HButton.vue')['default']
    HCheckList: typeof import('./../layouts/ui-kit/HCheckList.vue')['default']
    HDialog: typeof import('./../layouts/ui-kit/HDialog.vue')['default']
    HDropdown: typeof import('./../layouts/ui-kit/HDropdown.vue')['default']
    HDropdownMenu: typeof import('./../layouts/ui-kit/HDropdownMenu.vue')['default']
    HInput: typeof import('./../layouts/ui-kit/HInput.vue')['default']
    HKbd: typeof import('./../layouts/ui-kit/HKbd.vue')['default']
    HSelect: typeof import('./../layouts/ui-kit/HSelect.vue')['default']
    HSlideover: typeof import('./../layouts/ui-kit/HSlideover.vue')['default']
    HTabList: typeof import('./../layouts/ui-kit/HTabList.vue')['default']
    HToggle: typeof import('./../layouts/ui-kit/HToggle.vue')['default']
    HTooltip: typeof import('./../layouts/ui-kit/HTooltip.vue')['default']
    ImagePreview: typeof import('./../components/ImagePreview/index.vue')['default']
    ImagesUpload: typeof import('./../components/ImagesUpload/index.vue')['default']
    ImageUpload: typeof import('./../components/ImageUpload/index.vue')['default']
    ImgVerify: typeof import('./../components/ImgVerify/index.vue')['default']
    NotAllowed: typeof import('./../components/NotAllowed/index.vue')['default']
    PageHeader: typeof import('./../components/PageHeader/index.vue')['default']
    PageMain: typeof import('./../components/PageMain/index.vue')['default']
    Pagination: typeof import('./../components/ProTable/components/Pagination.vue')['default']
    PcasCascader: typeof import('./../components/PcasCascader/index.vue')['default']
    ProIconSelect: typeof import('./../components/ProIconSelect/index.vue')['default']
    ProTable: typeof import('./../components/ProTable/index.vue')['default']
    ProTableSelect: typeof import('./../components/ProTableSelect/index.vue')['default']
    ProTinymce: typeof import('./../components/ProTinymce/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/SearchBar/index.vue')['default']
    SearchForm: typeof import('./../components/SearchForm/index.vue')['default']
    SearchFormItem: typeof import('./../components/SearchForm/components/SearchFormItem.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    SystemInfo: typeof import('./../components/SystemInfo/index.vue')['default']
    TableColumn: typeof import('./../components/ProTable/components/TableColumn.vue')['default']
    Trend: typeof import('./../components/Trend/index.vue')['default']
  }
}
