// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		Auth: typeof import('./components/Auth/index.vue')['default'];
		AuthAll: typeof import('./components/AuthAll/index.vue')['default'];
		BatchActionBar: typeof import('./components/BatchActionBar/index.vue')['default'];
		BetterScroll: typeof import('./components/BetterScroll.vue')['default'];
		ColSetting: typeof import('./components/ProTable/components/ColSetting.vue')['default'];
		Copyright: typeof import('./components/Copyright/index.vue')['default'];
		Editor: typeof import('./components/Editor/index.vue')['default'];
		FileUpload: typeof import('./components/FileUpload/index.vue')['default'];
		FixedActionBar: typeof import('./components/FixedActionBar/index.vue')['default'];
		ImagePreview: typeof import('./components/ImagePreview/index.vue')['default'];
		ImagesUpload: typeof import('./components/ImagesUpload/index.vue')['default'];
		ImageUpload: typeof import('./components/ImageUpload/index.vue')['default'];
		ImportExcel: typeof import('./components/ImportExcel/index.vue')['default'];
		PageHeader: typeof import('./components/PageHeader/index.vue')['default'];
		PageMain: typeof import('./components/PageMain/index.vue')['default'];
		Pagination: typeof import('./components/ProTable/components/Pagination.vue')['default'];
		PcasCascader: typeof import('./components/PcasCascader/index.vue')['default'];
		ProTable: typeof import('./components/ProTable/index.vue')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
		SearchForm: typeof import('./components/SearchForm/index.vue')['default'];
		SearchFormItem: typeof import('./components/SearchForm/components/SearchFormItem.vue')['default'];
		SvgIcon: typeof import('./components/SvgIcon/index.vue')['default'];
		SystemInfo: typeof import('./components/SystemInfo/index.vue')['default'];
		Trend: typeof import('./components/Trend/index.vue')['default'];
	}
}
